project_name: lhdiff
release:
  github:
    owner: aslakhellesoy
    name: lhdiff
brews:
- install: |
    bin.install "lhdiff"
    man1.install "lhdiff.1"
  github:
    owner: aslakhellesoy
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/aslakhellesoy/lhdiff
  description: A Lightweight Hybrid Approach for Tracking Source Lines
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: lhdiff
  hooks:
    pre: make man
archives:
- id: gzip
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  - lhdiff.1
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
